/** Stable action names for audit_logs.action (single source of truth). */
export const AuditAction = {
  EVENT_CREATE: "event.create",
  EVENT_UPDATE: "event.update",
  EVENT_DELETE: "event.delete",
  SESSION_CREATE: "session.create",
  SESSION_UPDATE: "session.update",
  SESSION_DELETE: "session.delete",
  ATTENDEE_IMPORT: "attendee.import_csv",
  ATTENDEE_CHECK_IN: "attendee.check_in",
  ATTENDEE_BULK_CHECK_IN: "attendee.bulk_check_in",
  INVITE_CREATE: "invitation.create",
  INVITE_REVOKE: "invitation.revoke",
  INVITE_ACCEPT: "invitation.accept",
  MEMBER_ROLE_UPDATE: "member.role_update",
  SETTINGS_ORG_UPDATE: "settings.organization_update",
  SETTINGS_PROFILE_UPDATE: "settings.profile_update",
  VENUE_CREATE: "venue.create",
  VENUE_UPDATE: "venue.update",
  VENUE_DELETE: "venue.delete",
  PAYMENT_INTENT_CREATE: "payment.intent_create",
  PAYMENT_CONFIRMED: "payment.confirmed",
  PAYMENT_WEBHOOK: "payment.webhook_status",
  CONTENT_ENTITLEMENT_GRANT: "content.entitlement_grant",
  STUDIO_PACKAGING_GENERATE: "studio.packaging.generate",
  STUDIO_TIMED_SCRIPT_GENERATE: "studio.timed_script.generate",
  STUDIO_THUMBNAIL_GENERATE: "studio.thumbnail.generate",
  STUDIO_TTS_GENERATE: "studio.tts.generate",
  STUDIO_SUBTITLE_GENERATE: "studio.subtitle.generate",
  STUDIO_SCENE_RENDER: "studio.scene.render",
  STUDIO_VIDEO_ASSEMBLE: "studio.video.assemble",
  STUDIO_YOUTUBE_UPLOAD: "studio.youtube.upload",
} as const;

export const AuditEntityType = {
  CONTENT_PRODUCT: "content_product",
  EVENT: "event",
  SESSION: "session",
  ATTENDEE: "attendee",
  INVITATION: "organization_invitation",
  PROFILE: "profile",
  ORGANIZATION: "organization",
  VENUE: "venue",
  PAYMENT: "toss_payment",
  LEMON_ORDER: "lemon_order",
  STUDIO_EPISODE: "studio_episode",
  STUDIO_ARTIFACT: "studio_artifact",
} as const;
