/** Stable action names for audit_logs.action (single source of truth). */
export const AuditAction = {
  INVITE_CREATE: "invitation.create",
  INVITE_REVOKE: "invitation.revoke",
  INVITE_ACCEPT: "invitation.accept",
  MEMBER_ROLE_UPDATE: "member.role_update",
  SETTINGS_ORG_UPDATE: "settings.organization_update",
  SETTINGS_PROFILE_UPDATE: "settings.profile_update",
  PAYMENT_WEBHOOK: "payment.webhook_status",
  CONTENT_ENTITLEMENT_GRANT: "content.entitlement_grant",
  STUDIO_PACKAGING_GENERATE: "studio.packaging.generate",
  STUDIO_TIMED_SCRIPT_GENERATE: "studio.timed_script.generate",
  STUDIO_THUMBNAIL_GENERATE: "studio.thumbnail.generate",
  STUDIO_TTS_GENERATE: "studio.tts.generate",
  STUDIO_SUBTITLE_GENERATE: "studio.subtitle.generate",
  STUDIO_SCENE_RENDER: "studio.scene.render",
  STUDIO_SCENE_IMAGE_GENERATE: "studio.scene_image.generate",
  STUDIO_SCENE_IMAGE_PROMOTE: "studio.scene_image.promote",
  STUDIO_SCENE_IMAGE_DELETE: "studio.scene_image.delete",
  STUDIO_RUNWAY_I2V: "studio.runway.i2v",
  STUDIO_VIDEO_ASSEMBLE: "studio.video.assemble",
  STUDIO_YOUTUBE_UPLOAD: "studio.youtube.upload",
  STUDIO_CAPTIONS_GENERATE: "studio.captions.generate",
  STUDIO_BUFFER_SCHEDULE: "studio.buffer.schedule",
  STUDIO_BUFFER_CANCEL: "studio.buffer.cancel",
  STUDIO_BUFFER_RETRY: "studio.buffer.retry",
} as const;

export const AuditEntityType = {
  CONTENT_PRODUCT: "content_product",
  INVITATION: "organization_invitation",
  PROFILE: "profile",
  ORGANIZATION: "organization",
  LEMON_ORDER: "lemon_order",
  STUDIO_EPISODE: "studio_episode",
  STUDIO_ARTIFACT: "studio_artifact",
} as const;
